title: MiliPedia
author: ArtiPedia
email: artipedia243@gmail.com
description: > 
  Berita Seputar Militer dan Alutsista
baseurl: "/"
url: "https://militer.artipedia.id"
google_tag_manager: 
twitter_username:  
github_username:  ArtiPedia
instagram_username:  
social:
  name: ArtiPedia
  links:
    - https://twitter.com/ 
    - https://www.facebook.com/ 
    - https://www.linkedin.com/in/ 
    - https://plus.google.com/ 
    - https://github.com/ 
    - https://keybase.io/ 

disqus:
  shortname: MiliPedia

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title.html

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

encoding: UTF-8
